### ISSUE TITLE
Stream property disposal

### ISSUE THREAD

**Issue by timbell** [buttonsrtoys/mvvm_plus#41]
Is there a right way to clean up stream properties? I am calling `dispose` on them in the `dispose` method of my view models. But I then get an exception the next time a value is written to the stream:

```
Exception has occurred.
FlutterError (A StreamProperty<Player> was used after being disposed.
Once you have called dispose() on a StreamProperty<Player>, it can no longer be used.)
```

The call stack is as follows:

```
ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (d:\dev\flutter\packages\flutter\lib\src\foundation\change_notifier.dart:179)
ChangeNotifier.debugAssertNotDisposed (d:\dev\flutter\packages\flutter\lib\src\foundation\change_notifier.dart:186)
ChangeNotifier.notifyListeners (d:\dev\flutter\packages\flutter\lib\src\foundation\change_notifier.dart:382)
StreamProperty._getStream (c:\Users\tim_b\AppData\Local\Pub\Cache\hosted\pub.dev\mvvm_plus-1.4.3\lib\src\src.dart:589)
<asynchronous gap> (Unknown Source:0)
```

Note that my stream is long lived (actually an RxDart BehaviorSubject). Looking at the code, a solution might be to set a `_disposed` flag in `StreamProperty` when `dispose` is called and test on this in `_getStream`:

```
void _getStream(Stream<T> stream) async {
  _hasData = false;
  await for (final value in stream) {
    if (_disposed) {
      break;
    }
    _data = value;
    _hasData = true;
    notifyListeners();
  }
}
```

**Comment by buttonsrtoys** [comment]
Thanks for catching this. It as an oversight on my part. I'll add a `StreamProperty.cancel()` function that you can call in your dispose that will cancel the subscription. I can't get to this today, but will fix it up tomorrow or Friday at the latest.

**Comment by timbell** [comment]
Fantastic - thanks! I don't use it myself but there's perhaps a related issue with the `value` setter which makes a new call to `_getStream` ? Maybe `_getStream` should validate that the awaited stream is still the same as the current one and break out if it's not the case? `FutureProperty._getFuture` could have a similar test

**Comment by buttonsrtoys** [comment]
I just pushed version 1.5.0 and 1.5.1 which adds on override `StreamProperty.dispose()` which cancels the stream subscription on dispose. I also added a `StreamProperty.subscription` getter to give more granular control over the stream subscription, so you can do things like `StreamProperty.subscription.pause()` and `StreamProperty.subscription.resume()`. I also fixed the `StreamProperty.value` value setter.

**Comment by timbell** [comment]
That works well - thank-you!
